// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "../context/theme/ThemeContext";
// // 1. Impor "Interkom" yang baru kita buat
// import AuthProvider from "../components/AuthProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Devlens - xapi analyser",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         {/*
//           'ThemeProvider' membungkus 'AuthProvider'.
//           'AuthProvider' membungkus '{children}' (semua halaman Anda).
//         */}
//         <ThemeProvider>
//           {/* 2. Pasang "Interkom" di sini */}
//           <AuthProvider>{children}</AuthProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// 1. Tambahkan "use client" di baris paling atas
"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider, useThemeContext } from "../context/theme/ThemeContext";
import AuthProvider from "../components/AuthProvider";
import { Suspense } from "react"; // Suspense jika ada logic di ThemeProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Buat komponen baru untuk membaca context
function AppBody({ children }) {
  // 3. Panggil hook 'useThemeContext' DI DALAM komponen ini
  //    (Ini tidak bisa dilakukan di RootLayout langsung)
  const { isDark } = useThemeContext();

  // 4. Terapkan kelas 'dark' ke <html>
  return (
    <html lang="en" className={isDark ? "dark" : ""} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}

// 5. Modifikasi RootLayout utama
export default function RootLayout({ children }) {
  return (
    // AuthProvider dan ThemeProvider tetap membungkus SEMUANYA
    <AuthProvider>
      <ThemeProvider>
        {/* Suspense diperlukan karena AppBody menggunakan hook
          yang bergantung pada 'window' (via ThemeProvider).
        */}
        <Suspense
          fallback={
            <html lang="en">
              <body className="antialiased"></body>
            </html>
          }
        >
          <AppBody>{children}</AppBody>
        </Suspense>
      </ThemeProvider>
    </AuthProvider>
  );
}
